categories:
- Sequence Analysis
description: 'Convert a Primer Scheme .bed File to Amplicon Intervals'
long_description: |
  Convert a Primer Scheme .bed File to Amplicon Intervals
name: primer_scheme_to_amplicon_intervals
owner: public-health-bioinformatics
remote_repository_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/primer_scheme_to_amplicon_intervals
homepage_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/primer_scheme_to_amplicon_intervals
type: unrestricted
