categories:
- Sequence Analysis
description: Produce an HTML table report of BLAST results 
homepage_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/blast_report
long_description: |
  Produce an HTML table report of BLAST results 
name: blast_report
owner: public-health-bioinformatics
remote_repository_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/blast_report
type: unrestricted
