categories:
- Sequence Analysis
description: Screen abricate report for specific genes of interest
homepage_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/screen_abricate_report
long_description: |
  Screen abricate report for specific genes of interest
name: screen_abricate_report
owner: public-health-bioinformatics
remote_repository_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/screen_abricate_report
type: unrestricted
